server:
  port: 8085

spring:
  cloud:
    config:
      server:
        git:
           uri: https://github.com/vijayjadhav888/trendfusion
           searchPaths: '{application}'
           cloneOnStart: true
           

